// flow-typed signature: 96d65cedb608b110445c2f0cac1a3d25
// flow-typed version: <<STUB>>/lattice_v0.62.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
