// flow-typed signature: 62397dedf86a068ffed9d3efebcece23
// flow-typed version: <<STUB>>/lattice_v0.74.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
