// flow-typed signature: a16d8acddd46ad818c6be84ada4912c8
// flow-typed version: <<STUB>>/lattice-ui-kit_v0.46.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-ui-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-ui-kit' {
  declare module.exports: any;
}
