// flow-typed signature: ef070746e679ecface0feae4762d3ef8
// flow-typed version: <<STUB>>/react-dropzone_v11.3.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
