// flow-typed signature: 4a7137320a17b9cfde399267f3d17205
// flow-typed version: <<STUB>>/react-signature-canvas_v1.0.3/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-signature-canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-signature-canvas' {
  declare module.exports: any;
}
