// flow-typed signature: 8c2e783abfef3a045b9085a271d3fbc0
// flow-typed version: <<STUB>>/react-transition-group_v4.3.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transition-group' {
  declare module.exports: any;
}
