// flow-typed signature: fb2ab7ca030eba490beebd547f1ced80
// flow-typed version: <<STUB>>/styled-components_v4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
};
