// flow-typed signature: 037ef1e04bd2242131eea739143c2a24
// flow-typed version: <<STUB>>/xstate_v4.7.3/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xstate' {
  declare module.exports: any;
}
