// flow-typed signature: c39c5ccf4429210b021ce5200e9492cb
// flow-typed version: <<STUB>>/@rjsf/core_v2.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rjsf/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rjsf/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rjsf/core/dist/cjs/components/AddButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/ErrorList' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/ArrayField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/BooleanField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/DescriptionField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/MultiSchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/NullField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/NumberField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/ObjectField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/SchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/StringField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/TitleField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/fields/UnsupportedField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/Form' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/IconButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/AltDateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/AltDateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/BaseInput' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/CheckboxesWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/CheckboxWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/ColorWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/DateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/DateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/EmailWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/FileWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/HiddenWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/PasswordWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/RadioWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/RangeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/SelectWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/TextareaWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/TextWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/UpDownWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/components/widgets/URLWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/utils' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/validate' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/cjs/withTheme' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/editor.worker' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/AddButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/ErrorList' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/ArrayField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/BooleanField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/DescriptionField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/MultiSchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/NullField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/NumberField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/ObjectField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/SchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/StringField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/TitleField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/fields/UnsupportedField' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/Form' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/IconButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/AltDateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/AltDateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/BaseInput' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/CheckboxesWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/CheckboxWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/ColorWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/DateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/DateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/EmailWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/FileWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/HiddenWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/PasswordWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/RadioWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/RangeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/SelectWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/TextareaWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/TextWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/UpDownWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/components/widgets/URLWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/types' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/utils' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/validate' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/es/withTheme' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/json.worker' {
  declare module.exports: any;
}

declare module '@rjsf/core/dist/react-jsonschema-form' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/AddButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/ErrorList' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/ArrayField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/BooleanField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/DescriptionField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/MultiSchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/NullField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/NumberField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/ObjectField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/SchemaField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/StringField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/TitleField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/fields/UnsupportedField' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/Form' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/IconButton' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/AltDateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/AltDateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/BaseInput' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/CheckboxesWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/CheckboxWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/ColorWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/DateTimeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/DateWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/EmailWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/FileWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/HiddenWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/PasswordWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/RadioWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/RangeWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/SelectWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/TextareaWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/TextWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/UpDownWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/components/widgets/URLWidget' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/index' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/types' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/utils' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/validate' {
  declare module.exports: any;
}

declare module '@rjsf/core/lib/withTheme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rjsf/core/dist/cjs/components/AddButton.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/AddButton'>;
}
declare module '@rjsf/core/dist/cjs/components/ErrorList.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/ErrorList'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/ArrayField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/ArrayField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/BooleanField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/BooleanField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/DescriptionField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/DescriptionField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/index'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/MultiSchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/MultiSchemaField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/NullField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/NullField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/NumberField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/NumberField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/ObjectField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/ObjectField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/SchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/SchemaField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/StringField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/StringField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/TitleField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/TitleField'>;
}
declare module '@rjsf/core/dist/cjs/components/fields/UnsupportedField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/fields/UnsupportedField'>;
}
declare module '@rjsf/core/dist/cjs/components/Form.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/Form'>;
}
declare module '@rjsf/core/dist/cjs/components/IconButton.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/IconButton'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/AltDateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/AltDateTimeWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/AltDateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/AltDateWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/BaseInput.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/BaseInput'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/CheckboxesWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/CheckboxesWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/CheckboxWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/CheckboxWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/ColorWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/ColorWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/DateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/DateTimeWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/DateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/DateWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/EmailWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/EmailWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/FileWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/FileWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/HiddenWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/HiddenWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/index'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/PasswordWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/PasswordWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/RadioWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/RadioWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/RangeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/RangeWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/SelectWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/SelectWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/TextareaWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/TextareaWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/TextWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/TextWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/UpDownWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/UpDownWidget'>;
}
declare module '@rjsf/core/dist/cjs/components/widgets/URLWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/components/widgets/URLWidget'>;
}
declare module '@rjsf/core/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/index'>;
}
declare module '@rjsf/core/dist/cjs/types.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/types'>;
}
declare module '@rjsf/core/dist/cjs/utils.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/utils'>;
}
declare module '@rjsf/core/dist/cjs/validate.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/validate'>;
}
declare module '@rjsf/core/dist/cjs/withTheme.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/cjs/withTheme'>;
}
declare module '@rjsf/core/dist/editor.worker.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/editor.worker'>;
}
declare module '@rjsf/core/dist/es/components/AddButton.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/AddButton'>;
}
declare module '@rjsf/core/dist/es/components/ErrorList.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/ErrorList'>;
}
declare module '@rjsf/core/dist/es/components/fields/ArrayField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/ArrayField'>;
}
declare module '@rjsf/core/dist/es/components/fields/BooleanField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/BooleanField'>;
}
declare module '@rjsf/core/dist/es/components/fields/DescriptionField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/DescriptionField'>;
}
declare module '@rjsf/core/dist/es/components/fields/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/index'>;
}
declare module '@rjsf/core/dist/es/components/fields/MultiSchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/MultiSchemaField'>;
}
declare module '@rjsf/core/dist/es/components/fields/NullField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/NullField'>;
}
declare module '@rjsf/core/dist/es/components/fields/NumberField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/NumberField'>;
}
declare module '@rjsf/core/dist/es/components/fields/ObjectField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/ObjectField'>;
}
declare module '@rjsf/core/dist/es/components/fields/SchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/SchemaField'>;
}
declare module '@rjsf/core/dist/es/components/fields/StringField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/StringField'>;
}
declare module '@rjsf/core/dist/es/components/fields/TitleField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/TitleField'>;
}
declare module '@rjsf/core/dist/es/components/fields/UnsupportedField.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/fields/UnsupportedField'>;
}
declare module '@rjsf/core/dist/es/components/Form.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/Form'>;
}
declare module '@rjsf/core/dist/es/components/IconButton.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/IconButton'>;
}
declare module '@rjsf/core/dist/es/components/widgets/AltDateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/AltDateTimeWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/AltDateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/AltDateWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/BaseInput.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/BaseInput'>;
}
declare module '@rjsf/core/dist/es/components/widgets/CheckboxesWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/CheckboxesWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/CheckboxWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/CheckboxWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/ColorWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/ColorWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/DateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/DateTimeWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/DateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/DateWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/EmailWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/EmailWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/FileWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/FileWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/HiddenWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/HiddenWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/index'>;
}
declare module '@rjsf/core/dist/es/components/widgets/PasswordWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/PasswordWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/RadioWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/RadioWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/RangeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/RangeWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/SelectWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/SelectWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/TextareaWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/TextareaWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/TextWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/TextWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/UpDownWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/UpDownWidget'>;
}
declare module '@rjsf/core/dist/es/components/widgets/URLWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/components/widgets/URLWidget'>;
}
declare module '@rjsf/core/dist/es/index.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/index'>;
}
declare module '@rjsf/core/dist/es/types.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/types'>;
}
declare module '@rjsf/core/dist/es/utils.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/utils'>;
}
declare module '@rjsf/core/dist/es/validate.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/validate'>;
}
declare module '@rjsf/core/dist/es/withTheme.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/es/withTheme'>;
}
declare module '@rjsf/core/dist/json.worker.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/json.worker'>;
}
declare module '@rjsf/core/dist/react-jsonschema-form.js' {
  declare module.exports: $Exports<'@rjsf/core/dist/react-jsonschema-form'>;
}
declare module '@rjsf/core/lib/components/AddButton.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/AddButton'>;
}
declare module '@rjsf/core/lib/components/ErrorList.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/ErrorList'>;
}
declare module '@rjsf/core/lib/components/fields/ArrayField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/ArrayField'>;
}
declare module '@rjsf/core/lib/components/fields/BooleanField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/BooleanField'>;
}
declare module '@rjsf/core/lib/components/fields/DescriptionField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/DescriptionField'>;
}
declare module '@rjsf/core/lib/components/fields/index.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/index'>;
}
declare module '@rjsf/core/lib/components/fields/MultiSchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/MultiSchemaField'>;
}
declare module '@rjsf/core/lib/components/fields/NullField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/NullField'>;
}
declare module '@rjsf/core/lib/components/fields/NumberField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/NumberField'>;
}
declare module '@rjsf/core/lib/components/fields/ObjectField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/ObjectField'>;
}
declare module '@rjsf/core/lib/components/fields/SchemaField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/SchemaField'>;
}
declare module '@rjsf/core/lib/components/fields/StringField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/StringField'>;
}
declare module '@rjsf/core/lib/components/fields/TitleField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/TitleField'>;
}
declare module '@rjsf/core/lib/components/fields/UnsupportedField.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/fields/UnsupportedField'>;
}
declare module '@rjsf/core/lib/components/Form.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/Form'>;
}
declare module '@rjsf/core/lib/components/IconButton.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/IconButton'>;
}
declare module '@rjsf/core/lib/components/widgets/AltDateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/AltDateTimeWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/AltDateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/AltDateWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/BaseInput.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/BaseInput'>;
}
declare module '@rjsf/core/lib/components/widgets/CheckboxesWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/CheckboxesWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/CheckboxWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/CheckboxWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/ColorWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/ColorWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/DateTimeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/DateTimeWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/DateWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/DateWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/EmailWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/EmailWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/FileWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/FileWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/HiddenWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/HiddenWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/index.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/index'>;
}
declare module '@rjsf/core/lib/components/widgets/PasswordWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/PasswordWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/RadioWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/RadioWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/RangeWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/RangeWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/SelectWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/SelectWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/TextareaWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/TextareaWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/TextWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/TextWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/UpDownWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/UpDownWidget'>;
}
declare module '@rjsf/core/lib/components/widgets/URLWidget.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/components/widgets/URLWidget'>;
}
declare module '@rjsf/core/lib/index.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/index'>;
}
declare module '@rjsf/core/lib/types.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/types'>;
}
declare module '@rjsf/core/lib/utils.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/utils'>;
}
declare module '@rjsf/core/lib/validate.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/validate'>;
}
declare module '@rjsf/core/lib/withTheme.js' {
  declare module.exports: $Exports<'@rjsf/core/lib/withTheme'>;
}
