// flow-typed signature: 59eb5d5fbc45b7f72f1da9c3697ec632
// flow-typed version: <<STUB>>/@xstate/react_v0.8.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@xstate/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@xstate/react' {
  declare module.exports: any;
}
