// flow-typed signature: 289b1679ec6d10ff4c39623ae9cd613c
// flow-typed version: <<STUB>>/@storybook/addon-actions_v5.1.9/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}